<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'att_cod',
'id_cont_fk',
'att_type',
'att_file',
'sys_user',
'sys_time',
'cont_pre',
'cont_num',
'cont_vigencia',
'sys_date',
'sys_stat' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'att_cod' => array( 'import_field' ),
'id_cont_fk' => array( 'import_field1' ),
'att_type' => array( 'import_field2' ),
'att_file' => array( 'import_field3' ),
'sys_user' => array( 'import_field4' ),
'sys_time' => array( 'import_field6' ),
'cont_pre' => array( 'import_field5' ),
'cont_num' => array( 'import_field8' ),
'cont_vigencia' => array( 'import_field9' ),
'sys_date' => array( 'import_field7' ),
'sys_stat' => array( 'import_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field6',
'import_field',
'import_field5',
'import_field8',
'import_field9',
'import_field7',
'import_field10' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field6' => 'grid',
'import_field' => 'grid',
'import_field5' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field7' => 'grid',
'import_field10' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field6',
'import_field5',
'import_field8',
'import_field9',
'import_field7',
'import_field10' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field6',
'import_field',
'import_field5',
'import_field8',
'import_field9',
'import_field7',
'import_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'att_cod',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'id_cont_fk',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'att_type',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'att_file',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'sys_time',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cont_pre',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cont_num',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cont_vigencia',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'sys_date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'sys_stat',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>