<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'contractor_type',
'contractor_doc_id',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'contractor_address',
'contractor_phone',
'contractor_mobile',
'contractor_city',
'bank_name',
'bank_cta_type',
'bank_cta_number',
'active',
'contractor_doc_dv' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'contractor_type' => array( 'import_field1' ),
'contractor_doc_id' => array( 'import_field2' ),
'contractor_nombresfull' => array( 'import_field8' ),
'contractor_email' => array( 'import_field9' ),
'contractor_email_mincit' => array( 'import_field10' ),
'contractor_address' => array( 'import_field11' ),
'contractor_phone' => array( 'import_field12' ),
'contractor_mobile' => array( 'import_field13' ),
'contractor_city' => array( 'import_field14' ),
'bank_name' => array( 'import_field15' ),
'bank_cta_type' => array( 'import_field16' ),
'bank_cta_number' => array( 'import_field17' ),
'active' => array( 'import_field28' ),
'contractor_doc_dv' => array( 'import_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field28',
'import_field' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field28' => 'grid',
'import_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field28',
'import_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field28',
'import_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'contractor_type',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'contractor_doc_id',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'contractor_nombresfull',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'contractor_email',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'contractor_email_mincit',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'contractor_address',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'contractor_phone',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'contractor_mobile',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'contractor_city',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'bank_name',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'bank_cta_type',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'bank_cta_number',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'active',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'contractor_doc_dv',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>