<?php
			$optionsArray = array( 'master' => array( 'q_bandejaentrada_supervisores' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'id_cont_fk',
'inf_consecutivo',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_valorcontrato',
'inf_valor_pago',
'avgavance',
'inf_st' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array( 'id_cont_fk',
'inf_consecutivo',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_valorcontrato',
'inf_valor_pago',
'avgavance',
'inf_st' ),
'fieldItems' => array( 'id_cont_fk' => array( 'integrated_edit_field',
'integrated_edit_field8',
'integrated_edit_field9' ),
'inf_consecutivo' => array( 'integrated_edit_field1',
'integrated_edit_field10',
'integrated_edit_field11' ),
'inf_fecharep_i' => array( 'integrated_edit_field2',
'integrated_edit_field12',
'integrated_edit_field13' ),
'inf_fecharep_f' => array( 'integrated_edit_field3',
'integrated_edit_field14',
'integrated_edit_field15' ),
'inf_valorcontrato' => array( 'integrated_edit_field4',
'integrated_edit_field18',
'integrated_edit_field19' ),
'inf_valor_pago' => array( 'integrated_edit_field5',
'integrated_edit_field16',
'integrated_edit_field17' ),
'avgavance' => array( 'integrated_edit_field6',
'integrated_edit_field20',
'integrated_edit_field21' ),
'inf_st' => array( 'integrated_edit_field7',
'integrated_edit_field22',
'integrated_edit_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field8',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field1',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field2',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field3',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field5',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field4',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field6',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field7',
'integrated_edit_field23' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'update_records' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field23' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c24' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7' ),
'edit_field_label' => array( 'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field20',
'integrated_edit_field22' ),
'edit_field_tooltip' => array( 'integrated_edit_field9',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field15',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field23' ),
'edit_view' => array( 'edit_view' ),
'update_records' => array( 'update_records' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'id_cont_fk_fieldblock' ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inf_consecutivo_fieldblock' ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'inf_fecharep_i_fieldblock' ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'inf_fecharep_f_fieldblock' ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'inf_valor_pago_fieldblock' ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'inf_valorcontrato_fieldblock' ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'avgavance_fieldblock' ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'inf_st_fieldblock' ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 8 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array( 'update_records' => array( 'tag' => 'UPDATE_N_RECORDS',
'type' => 2 ) ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => true ) );
			$pageArray = array( 'id' => 'edit1',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c5' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c6' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ),
array( 'cell' => 'c21' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c24' ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field8' ),
'field' => 'id_cont_fk' ),
'c2' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field' ),
'field' => 'id_cont_fk' ),
'c' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field9' ),
'field' => 'id_cont_fk' ),
'c5' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field10' ),
'field' => 'inf_consecutivo' ),
'c3' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field1' ),
'field' => 'inf_consecutivo' ),
'c6' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field11' ),
'field' => 'inf_consecutivo' ),
'c7' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field12' ),
'field' => 'inf_fecharep_i' ),
'c8' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field2' ),
'field' => 'inf_fecharep_i' ),
'c9' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field13' ),
'field' => 'inf_fecharep_i' ),
'c10' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field14' ),
'field' => 'inf_fecharep_f' ),
'c11' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field3' ),
'field' => 'inf_fecharep_f' ),
'c12' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field15' ),
'field' => 'inf_fecharep_f' ),
'c13' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field16' ),
'field' => 'inf_valor_pago' ),
'c14' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field5' ),
'field' => 'inf_valor_pago' ),
'c15' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field17' ),
'field' => 'inf_valor_pago' ),
'c16' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field18' ),
'field' => 'inf_valorcontrato' ),
'c17' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field4' ),
'field' => 'inf_valorcontrato' ),
'c18' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field19' ),
'field' => 'inf_valorcontrato' ),
'c19' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field20' ),
'field' => 'avgavance' ),
'c20' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field6' ),
'field' => 'avgavance' ),
'c21' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field21' ),
'field' => 'avgavance' ),
'c22' => array( 'model' => 'c4',
'items' => array( 'integrated_edit_field22' ),
'field' => 'inf_st' ),
'c23' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field7' ),
'field' => 'inf_st' ),
'c24' => array( 'model' => 'c2',
'items' => array( 'integrated_edit_field23' ),
'field' => 'inf_st' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => true ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field' => array( 'field' => 'id_cont_fk',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field1' => array( 'field' => 'inf_consecutivo',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field2' => array( 'field' => 'inf_fecharep_i',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field3' => array( 'field' => 'inf_fecharep_f',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field4' => array( 'field' => 'inf_valorcontrato',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field5' => array( 'field' => 'inf_valor_pago',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field6' => array( 'field' => 'avgavance',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field7' => array( 'field' => 'inf_st',
'type' => 'edit_field',
'updateOnEdit' => true ),
'integrated_edit_field8' => array( 'type' => 'edit_field_label',
'field' => 'id_cont_fk' ),
'integrated_edit_field9' => array( 'type' => 'edit_field_tooltip',
'field' => 'id_cont_fk' ),
'integrated_edit_field10' => array( 'type' => 'edit_field_label',
'field' => 'inf_consecutivo' ),
'edit_view' => array( 'type' => 'edit_view' ),
'update_records' => array( 'type' => 'update_records' ),
'integrated_edit_field11' => array( 'type' => 'edit_field_tooltip',
'field' => 'inf_consecutivo' ),
'integrated_edit_field12' => array( 'type' => 'edit_field_label',
'field' => 'inf_fecharep_i' ),
'integrated_edit_field13' => array( 'type' => 'edit_field_tooltip',
'field' => 'inf_fecharep_i' ),
'integrated_edit_field14' => array( 'type' => 'edit_field_label',
'field' => 'inf_fecharep_f' ),
'integrated_edit_field15' => array( 'type' => 'edit_field_tooltip',
'field' => 'inf_fecharep_f' ),
'integrated_edit_field16' => array( 'type' => 'edit_field_label',
'field' => 'inf_valor_pago' ),
'integrated_edit_field17' => array( 'type' => 'edit_field_tooltip',
'field' => 'inf_valor_pago' ),
'integrated_edit_field18' => array( 'type' => 'edit_field_label',
'field' => 'inf_valorcontrato' ),
'integrated_edit_field19' => array( 'type' => 'edit_field_tooltip',
'field' => 'inf_valorcontrato' ),
'integrated_edit_field20' => array( 'type' => 'edit_field_label',
'field' => 'avgavance' ),
'integrated_edit_field21' => array( 'type' => 'edit_field_tooltip',
'field' => 'avgavance' ),
'integrated_edit_field22' => array( 'type' => 'edit_field_label',
'field' => 'inf_st' ),
'integrated_edit_field23' => array( 'type' => 'edit_field_tooltip',
'field' => 'inf_st' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>