<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_cont',
'cont_nit_contra_ta',
'cont_estado',
'numcontrato',
'pre_contnumero',
'contnumero',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_secop_enlace',
'documento_id',
'nombres',
'apellidos',
'cargo_id',
'dependencia_id',
'sup_fechanot',
'sup_mailnot',
'sup_status',
'idusrglobal_fk' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'import_field' ),
'cont_nit_contra_ta' => array( 'import_field1' ),
'cont_estado' => array( 'import_field2' ),
'numcontrato' => array( 'import_field3' ),
'pre_contnumero' => array( 'import_field4' ),
'contnumero' => array( 'import_field5' ),
'cont_ano' => array( 'import_field6' ),
'cont_codrubro' => array( 'import_field7' ),
'cont_catalogo_presupuestal' => array( 'import_field8' ),
'cont_fecha_inicio' => array( 'import_field9' ),
'cont_fechafinal' => array( 'import_field10' ),
'cont_periodicidad' => array( 'import_field11' ),
'cont_valorinicial' => array( 'import_field12' ),
'cont_valormensual' => array( 'import_field13' ),
'cont_secop_enlace' => array( 'import_field14' ),
'documento_id' => array( 'import_field15' ),
'nombres' => array( 'import_field16' ),
'apellidos' => array( 'import_field17' ),
'cargo_id' => array( 'import_field18' ),
'dependencia_id' => array( 'import_field19' ),
'sup_fechanot' => array( 'import_field20' ),
'sup_mailnot' => array( 'import_field21' ),
'sup_status' => array( 'import_field22' ),
'idusrglobal_fk' => array( 'import_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_cont',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cont_estado',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'numcontrato',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'pre_contnumero',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'contnumero',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cont_ano',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cont_codrubro',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cont_fecha_inicio',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cont_fechafinal',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cont_periodicidad',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'cont_valorinicial',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'cont_valormensual',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cont_secop_enlace',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'documento_id',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'nombres',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'apellidos',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'cargo_id',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'dependencia_id',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'sup_fechanot',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'sup_mailnot',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'sup_status',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'idusrglobal_fk',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>