<?php
			$optionsArray = array( 'totals' => array( 'interventor_id' => array( 'totalsType' => '' ),
'cont_hash_fk' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'idusrglobal_fk' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'documento_id' => array( 'totalsType' => '' ),
'nombres' => array( 'totalsType' => '' ),
'apellidos' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'documento' => array( 'totalsType' => '' ),
'nombre_razon' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'sup_status' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'interventor_id',
'sys_user',
'documento',
'nombre_razon',
'cont_estado',
'contnumero',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_valormensual',
'cont_hash_fk',
'idusrglobal_fk',
'cont_ano',
'prenumero',
'numregistro',
'cont_periodicidad',
'cont_informessug',
'cont_valorinicial',
'cont_acta_liquidacion',
'cont_objeto',
'cont_obligaciones',
'cont_plazo' ),
'exportFields' => array( 'interventor_id',
'sys_user',
'documento',
'nombre_razon',
'cont_estado',
'contnumero',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_valormensual',
'cont_hash_fk',
'idusrglobal_fk',
'cont_ano',
'prenumero',
'numregistro',
'cont_periodicidad',
'cont_informessug',
'cont_valorinicial',
'cont_acta_liquidacion',
'cont_objeto',
'cont_obligaciones',
'cont_plazo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'interventor_id' => array( 'export_field' ),
'sys_user' => array( 'export_field1' ),
'documento' => array( 'export_field7' ),
'nombre_razon' => array( 'export_field8' ),
'cont_estado' => array( 'export_field9' ),
'contnumero' => array( 'export_field10' ),
'cont_fecha_inicio' => array( 'export_field11' ),
'cont_fechafinal' => array( 'export_field12' ),
'cont_valormensual_base' => array( 'export_field13' ),
'cont_valormensual_iva' => array( 'export_field14' ),
'cont_valormensual' => array( 'export_field15' ),
'cont_hash_fk' => array( 'export_field2' ),
'idusrglobal_fk' => array( 'export_field3' ),
'cont_ano' => array( 'export_field4' ),
'prenumero' => array( 'export_field5' ),
'numregistro' => array( 'export_field6' ),
'cont_periodicidad' => array( 'export_field16' ),
'cont_informessug' => array( 'export_field17' ),
'cont_valorinicial' => array( 'export_field18' ),
'cont_acta_liquidacion' => array( 'export_field19' ),
'cont_objeto' => array( 'export_field20' ),
'cont_obligaciones' => array( 'export_field21' ),
'cont_plazo' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'interventor_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'documento',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'nombre_razon',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'cont_estado',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'contnumero',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cont_fecha_inicio',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cont_fechafinal',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'cont_valormensual_base',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'cont_valormensual_iva',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cont_valormensual',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'cont_hash_fk',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'idusrglobal_fk',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cont_ano',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'prenumero',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'numregistro',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'cont_periodicidad',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'cont_informessug',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'cont_valorinicial',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'cont_acta_liquidacion',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'cont_objeto',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'cont_obligaciones',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'cont_plazo',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>