<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'informe_intersup_plan_pagos' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'documento',
'nombre_razon',
'cont_estado',
'contnumero',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_valormensual',
'cont_ano',
'prenumero',
'numregistro',
'cont_periodicidad',
'cont_informessug',
'cont_valorinicial',
'cont_acta_liquidacion',
'cont_objeto',
'cont_obligaciones',
'cont_plazo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'documento' => array( 'integrated_edit_field7' ),
'nombre_razon' => array( 'integrated_edit_field8' ),
'cont_estado' => array( 'integrated_edit_field9' ),
'contnumero' => array( 'integrated_edit_field10' ),
'cont_fecha_inicio' => array( 'integrated_edit_field11' ),
'cont_fechafinal' => array( 'integrated_edit_field12' ),
'cont_valormensual_base' => array( 'integrated_edit_field13' ),
'cont_valormensual_iva' => array( 'integrated_edit_field14' ),
'cont_valormensual' => array( 'integrated_edit_field15' ),
'cont_ano' => array( 'integrated_edit_field4' ),
'prenumero' => array( 'integrated_edit_field5' ),
'numregistro' => array( 'integrated_edit_field6' ),
'cont_periodicidad' => array( 'integrated_edit_field16' ),
'cont_informessug' => array( 'integrated_edit_field17' ),
'cont_valorinicial' => array( 'integrated_edit_field18' ),
'cont_acta_liquidacion' => array( 'integrated_edit_field19' ),
'cont_objeto' => array( 'integrated_edit_field20' ),
'cont_obligaciones' => array( 'integrated_edit_field21' ),
'cont_plazo' => array( 'integrated_edit_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header',
'integrated_edit_field10',
'text',
'integrated_edit_field4' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close' ),
'grid' => array( 'section2',
'section1',
'section' ),
'section' => array( 'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field21' ),
'section1' => array( 'integrated_edit_field19',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field11',
'integrated_edit_field12' ),
'section2' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field15',
'integrated_edit_field9',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field18' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array( 'back_button',
'close_button' ) ),
'itemForms' => array( 'view_header' => 'top',
'integrated_edit_field10' => 'top',
'text' => 'top',
'integrated_edit_field4' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'section2' => 'grid',
'section1' => 'grid',
'section' => 'grid',
'integrated_edit_field20' => 'section',
'integrated_edit_field22' => 'section',
'integrated_edit_field21' => 'section',
'integrated_edit_field19' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field5' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field15' => 'section2',
'integrated_edit_field9' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field14' => 'section2',
'integrated_edit_field18' => 'section2' ),
'itemLocations' => array( 'section2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field20' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field21' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field19' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field5' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field14' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c8' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'integrated_edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22' ),
'edit_field' => array( 'integrated_edit_field10',
'integrated_edit_field4' ),
'section' => array( 'section',
'section1',
'section2' ),
'text' => array( 'text' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section2' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header',
'integrated_edit_field10',
'text',
'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ),
'c' => array( 'model' => 'c3',
'items' => array( 'section1' ),
'useFullWidth' => true ),
'c4' => array( 'model' => 'c3',
'items' => array( 'section' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true,
'width' => '100px' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ),
'useFullWidth' => true,
'width' => '100px' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ),
'useFullWidth' => true,
'width' => '100px' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'q_informes_supervision_activos',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'integrated_edit_field7' => array( 'field' => 'documento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'nombre_razon',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'cont_estado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'contnumero',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field11' => array( 'field' => 'cont_fecha_inicio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'cont_fechafinal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'cont_valormensual_base',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'cont_valormensual_iva',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'cont_valormensual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'cont_ano',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field5' => array( 'field' => 'prenumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'numregistro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'cont_periodicidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'cont_informessug',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'cont_valorinicial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'cont_acta_liquidacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'cont_objeto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'cont_obligaciones',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'cont_plazo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Objeto / Obligaciones / Plazo',
'type' => 0 ),
'location' => 'section',
'initiallyClosed' => true ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Información básica',
'type' => 0 ),
'location' => 'section1' ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Información presupuestal',
'type' => 0 ),
'location' => 'section2',
'initiallyClosed' => true ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'de',
'type' => 0 ) ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>