<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_contrato  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		if($data['cont_estado'] == 2)
{
$record["cont_estado_css"]='background:yellow;color:black;';
}

if($data['cont_estado'] == 3)
{
$record["cont_estado_css"]='background:green;color:white;';
}

// Finaliza contratos de forma automática, cuendo la fecha actual es mayo a la fecha de finalización del contrato

$sql = DB::prepareSQL("UPDATE
dbct.contrato
SET
dbct.contrato.cont_estado = 3
WHERE dbct.contrato.cont_fechafinal < CURDATE();");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
